userstories/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views import generic

from material.frontend import urls as frontend_urls

urlpatterns = [
    url(r'^$', generic.RedirectView.as_view(url='/webapp/anwendungen/', permanent=False)),
    url(r'^admin/', admin.site.urls),
    url(r'', include(frontend_urls)),

]

userstories/webapp/urls.py
from django.conf.urls import url, include
from django.views import generic

from . import views

urlpatterns = [
    url('^$', generic.RedirectView.as_view(
         url='./userstories/'), name="index"),
    url('^anwendungen/', include(views.AnwendungenViewSet().urls)),
    url('^userstories/', include(views.UserstoriesViewSet().urls)),
    url('^rollen/', include(views.RollenViewSet().urls)),
    url('^schlagworte/', include(views.SchlagworteViewSet().urls)),
    url('^glossarentraege/', include(views.GlossareintraegeViewSet().urls)),
    url('^notizen/', include(views.NotizenViewSet().urls)),
]

userstories/webapp/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
import os
import subprocess # PDF File Preview
from django.db.models.signals import post_save
from django.conf import settings

class Anwendungen(models.Model):
    titel = models.CharField(max_length=150)
    beschreibung = models.TextField(blank=True, verbose_name=_('Beschreibung'))

    class Meta:
        verbose_name = _('Anwendung')
        verbose_name_plural = _('Anwendungen')
        db_table = 'anwendungen'

    def __str__(self):
        return "{}".format(self.titel)

    def get_absolute_url(self):
        return "/webapp/anwendungen/{}/detail".format(self.id)

class Rollen(models.Model):
    anwendung = models.ForeignKey(Anwendungen, blank=True, on_delete=models.CASCADE, verbose_name=_('Anwendung'))
    rolle = models.CharField(max_length=250, verbose_name=_('Rolle'))
    beschreibung = models.TextField(blank=True, verbose_name=_('Beschreibung'))

    class Meta:
        verbose_name = _('Rolle')
        verbose_name_plural = _('Rollen')
        db_table = 'rollen'

    def __str__(self):
        return "{}".format(self.rolle)

    def get_absolute_url(self):
        return "/webapp/rollen/{}/detail".format(self.id)

class Schlagworte(models.Model):
    schlagwort = models.CharField(max_length=250)
    class Meta:
        verbose_name = _('Schlagwort')
        verbose_name_plural = _('Schlagworte')
        db_table = 'schlagworte'

    def __str__(self):
        return "{}".format(self.schlagwort)

    def get_absolute_url(self):
        return "/webapp/schlagworte/{}/detail".format(self.id)

class Glossareintraege(models.Model):
    titel = models.CharField(max_length=250)
    beschreibung = models.TextField(blank=True, verbose_name=_('Beschreibung'))

    class Meta:
        verbose_name = _('Glossareintrag')
        verbose_name_plural = _('Glossareinträge')
        db_table = 'glossarentraege'

    def __str__(self):
        return "{}".format(self.titel)

    def get_absolute_url(self):
        return "/webapp/glossarentraege/{}/detail".format(self.id)

class Userstories(models.Model):
    anwendung = models.ForeignKey(Anwendungen, blank=True, on_delete=models.CASCADE, verbose_name=_('Anwendung'))
    titel = models.CharField(max_length=150)
    rolle = models.ForeignKey(Rollen, blank=True, on_delete=models.CASCADE, verbose_name=_('Als...'))
    text_als = models.TextField(verbose_name=_('Möchte ich...'))
    text_damit = models.TextField(verbose_name=_('Damit ich...'))

    schlagworte = models.ManyToManyField(Schlagworte, blank=True, verbose_name=_('Schlagworte'))
    erfuellungsgrad = models.PositiveSmallIntegerField(verbose_name=_('Erfüllungsgrad'))

    class Meta:
        verbose_name = _('Userstory')
        verbose_name_plural = _('Userstories')
        db_table = 'userstories'

    def __str__(self):
        return "{}".format(self.titel)

    def color(self):
        if self.erfuellungsgrad == 100:
            return "green darken-1"
        if self.erfuellungsgrad > 80:
            return "green lighten-4"
        elif self.erfuellungsgrad < 30:
            return "deep-orange darken-1"
        else:
            return "orange lighten-3"

    def get_absolute_url(self):
        return "/webapp/userstories/{}/detail".format(self.id)


class Notizen(models.Model):
    text = models.TextField()

    datum = models.DateTimeField(auto_now_add=True)

    updated_at = models.DateTimeField(auto_now=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    userstory = models.ForeignKey(Userstories, blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('Notiz')
        verbose_name_plural = _('Notizen')
        db_table = 'notizen'

    def __str__(self):
        return "{}".format(self.text[:20])

    def get_title(self):
        return self.text[:30]

    def get_absolute_url(self):
        return "/webapp/notizen/{}/detail".format(self.id)

userstories/webapp/views.py
import json
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.shortcuts import get_object_or_404, render
from django.utils.translation import ugettext, ugettext_lazy as _
from django.views import generic

from material.frontend.views import ModelViewSet, ListModelView
from material import Layout, Row, Fieldset

from . import models # forms

class UserstoriesViewSet(ModelViewSet):
    model = models.Userstories
    list_display = ('titel','rolle','erfuellungsgrad')
    list_filter = ['titel', 'rolle', ]
    search_fields = ['titel', 'rolle',]

class RollenViewSet(ModelViewSet):
    model = models.Rollen
    list_display = ('rolle',)

class SchlagworteViewSet(ModelViewSet):
    model = models.Schlagworte
    list_display = ('schlagwort',)

class GlossareintraegeViewSet(ModelViewSet):
    model = models.Glossareintraege
    list_display = ('titel', 'beschreibung')

class AnwendungenViewSet(ModelViewSet):
    model = models.Anwendungen
    list_display = ('titel', 'beschreibung')

class NotizenViewSet(ModelViewSet):
    model = models.Notizen
    list_display = ('text','user','datum')

userstories/webapp/templates/material/base_site.html
{% block footer %}
<div class="page-footer">
This is a Test Footer.
</div>
{% endblock footer%}

userstories/webapp/templates/webapp/anwendungen_detail.html
{% extends 'material/frontend/views/detail.html' %}
{% load i18n material_frontend humanize %}

{% block breadcrumbs_items %}
<a class="active">{{ object }}</a>
{% endblock %}

{% block content %}
<div class="left-panel">

  <div class="card">
    <div class="card-content">
      <div class="card-title">{{ object }}</div>
      <p>{{ object.beschreibung }}</p>
    </div>
    <div class="card-action">
      <div class="right-align">
        {% if delete_url %}<a class="waves-effect waves-light btn red white-text" href="{{ delete_url }}">{% trans 'Delete' %}</a>{% endif %}
        {% if change_url %}<a class="waves-effect waves-light btn white-text" href="{{ change_url }}">{% trans 'Change' %}</a>{% endif %}
      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-content">
      <div class="card-title">{{ object.rollen_set.all.count }}  {% trans 'Rollen' %}</div>
      <div class="row">
        {% for rolle in object.rollen_set.all|slice:":10" %}
        <div class="col s8">
          <div class="card">
            <div class="card-content">
              <div class="card-title">{{ rolle.rolle }}</div>
              <p>{{ rolle.beschreibung }}</p>
              <div class="secondary-content">{{ rolle.userstories_set.count }} Userstories </div>
            </div>
            <div class="card-action">
              <a href='{{ rolle.get_absolute_url }}'>Details</a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      <a href="/webapp/rollen/add/" class="btn-floating btn-small waves-effect waves-light green"><i class="material-icons">add</i></a>

    </div>
  </div>


  <div class="card">
    <div class="card-content">
      <div class="card-title">{{ object.userstories_set.all.count }} {% trans 'Userstories' %}</div>
      <div class="row">
        {% for userstory in object.userstories_set.all|slice:":10" %}
        <div class="col s8">
          <div class="card {{ userstory.color }}">
            <div class="card-content white-text" >
              <p>Als <a href="{{ userstory.rolle.get_absolute_url}}">{{userstory.rolle}}</a> möchte ich {{ userstory.text_als }} damit ich {{ userstory.text_damit }}.</p>
              <div class="secondary-content white-text">Erfüllungsgrad {{ userstory.erfuellungsgrad }}%</div>

            </div>
            <div class="card-action white-text">
              <a href='{{ userstory.get_absolute_url }}'>Details</a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      <a href="/webapp/userstories/add/" class="btn-floating btn-small waves-effect waves-light green"><i class="material-icons">add</i></a>

    </div>
  </div>


  {% block contentfooter%}

  {% comment %}
  This works. However, the Footer is not inbeetween <footer> tags.
  {% endcomment %}

  <div class="row black">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Footer Content</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2014 Copyright Text
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
  {% endblock %}

</div>

{% endblock %}

{% comment %}
This does't seem to work. The footer appeares in the middle of the page, not at the bottom.
{% endcomment %}

{% block footer %}
<div class="row black">
  <div class="row">
    <div class="col l6 s12">
      <h5 class="white-text">Footer Content</h5>
      <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
    </div>
    <div class="col l4 offset-l2 s12">
      <h5 class="white-text">Links</h5>
      <ul>
        <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
        <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
        <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
        <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
      </ul>
    </div>
  </div>
</div>
<div class="footer-copyright">
  <div class="container">
    © 2014 Copyright Text
    <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
  </div>
</div>

{% endblock footer %}

userstories/webapp/templates/webapp/menu.html
{% load i18n %}
<ul>
    <li><a href="{% url 'webapp:anwendungen_list' %}">{% trans 'Anwendungen' %}</a></li>
    <li><a href="{% url 'webapp:userstories_list' %}">{% trans 'Userstories' %}</a></li>
    <li><a href="{% url 'webapp:rollen_list' %}">{% trans 'Rollen' %}</a></li>
    <li><a href="{% url 'webapp:glossareintraege_list' %}">{% trans 'Glossar' %}</a></li>
    <li><a href="{% url 'webapp:schlagworte_list' %}">{% trans 'Schlagworte' %}</a></li>
    <li><a href="{% url 'webapp:notizen_list' %}">{% trans 'Notizen' %}</a></li>
</ul>

userstories/webapp/templates/webapp/rollen_detail.html
{% extends 'material/frontend/views/detail.html' %}
{% load i18n material_frontend humanize %}

{% block breadcrumbs_items %}
<a href="{{ object.anwendung.get_absolute_url }}">{{ object.anwendung }}</a>
<a class="active">{{ object }}</a>
{% endblock %}

{% block content %}
<div class="left-panel">

  <div class="card">
    <div class="card-content">
      <div class="card-title">{{ object }}</div>
      <p>{{ object.beschreibung }}</p>
    </div>
    <div class="card-action">
        <div class="right-align">
            {% if delete_url %}<a class="waves-effect waves-light btn red white-text" href="{{ delete_url }}">{% trans 'Delete' %}</a>{% endif %}
            {% if change_url %}<a class="waves-effect waves-light btn white-text" href="{{ change_url }}">{% trans 'Change' %}</a>{% endif %}
        </div>
    </div>
  </div>

  <div class="card">
    <div class="card-content">
      <div class="card-title">{{ object.userstories_set.all.count }} {% trans 'Userstories' %}</div>
      <div class="row">
        {% for userstory in object.userstories_set.all|slice:":10" %}
          <div class="col s8">
            <div class="card">
              <div class="card-content">
                <p>Als <a href="{{ userstory.rolle.get_absolute_url}}">{{userstory.rolle}}</a> möchte ich {{ userstory.text_als }} damit ich {{ userstory.text_damit }}.</p>
                <div class="secondary-content">Erfüllungsgrad {{ userstory.erfuellungsgrad }}%</div>

              </div>
              <div class="card-action">
                <a href='{{ userstory.get_absolute_url }}'>Details</a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>

</div>


{% endblock %}

userstories/webapp/templates/webapp/userstories_detail.html
{% extends 'material/frontend/views/detail.html' %}
{% load i18n material_frontend humanize %}


{% block breadcrumbs_items %}
<a href="{{ object.anwendung.get_absolute_url }}">{{ object.anwendung }}</a>
<a class="active">{{ object }}</a>
{% endblock %}

{% block content %}
<div class="left-panel">

  <div class="card">
    <div class="card-content">
      <div class="card-title">{{ object }}</div>

      <div>
      Als <b>{{ object.rolle }}</b> möchte ich {{ object.text_als }} damit ich {{ object.text_damit }}
      </div>
      <div class="secondary-content">Erfüllungsgrad: <b>{{ object.erfuellungsgrad }}%</b></div>
    </div>
    <div class="card-action">
        <div class="right-align">
            {% if delete_url %}<a class="waves-effect waves-light btn red white-text" href="{{ delete_url }}">{% trans 'Delete' %}</a>{% endif %}
            {% if change_url %}<a class="waves-effect waves-light btn white-text" href="{{ change_url }}">{% trans 'Change' %}</a>{% endif %}
        </div>
    </div>
  </div>

  <div class="card">
      <div class="card-content">
          <div class="card-title">{% trans 'Notizen' %}</div>
          <table>
              <thead>
                  <tr>
                      <td>{% trans 'Datum' %}</td>
                      <td>{% trans 'Benutzer' %}</td>
                      <td>{% trans 'Text' %}</td>
                  </tr>
              </thead>
              <tbody>
                  {% for notiz in object.notizen_set.all|slice:":10" %}
                  <tr>
                      <td>{{notiz.datum}}</td>
                      <td>{{notiz.user}}</td>
                      <td>

                        <p><a href="{{ notiz.get_absolute_url }}">{{notiz.text}}</a></p>
                      </td>
                  </tr>
                  {% endfor %}
              </tbody>
          </table>
      </div>

  </div>

</div>


{% endblock %}